### ISSUE TITLE
Error built

### ISSUE THREAD

**Issue by soilland** [fu-sen/CloudflarePages-MkDocs#2]
I tried to built the repo Soilland/Meal-Wiki

When I added the content (nav:)  into .yml, cloudflare said built error

Log here

`17:59:15.036	Initializing build environment. This may take up to a few minutes to complete
18:01:42.044	Success: Finished initializing build environment
18:01:42.044	Cloning repository...
18:01:44.900	Success: Finished cloning repository files
18:01:46.005	Installing dependencies
18:01:46.009	Python version set to 3.7
18:01:46.970	v12.18.0 is already installed.
18:01:47.502	Now using node v12.18.0 (npm v6.14.4)
18:01:47.548	Started restoring cached build plugins
18:01:47.552	Finished restoring cached build plugins
18:01:47.689	Attempting ruby version 2.7.1, read from environment
18:01:48.771	Using ruby version 2.7.1
18:01:49.054	Using PHP version 5.6
18:01:49.054	Installing pip dependencies
18:01:49.054	Started restoring cached pip cache
18:01:49.096	Finished restoring cached pip cache
18:01:49.627	Collecting mkdocs
18:01:49.654	  Downloading mkdocs-1.2.3-py3-none-any.whl (6.4 MB)
18:01:49.940	Collecting mkdocs-bootswatch
18:01:49.949	  Downloading mkdocs_bootswatch-1.1-py2.py3-none-any.whl (560 kB)
18:01:50.102	Collecting mkdocs-minify-plugin
18:01:50.111	  Downloading mkdocs-minify-plugin-0.5.0.tar.gz (3.4 kB)
18:01:50.477	Collecting click>=3.3
18:01:50.483	  Downloading click-8.0.3-py3-none-any.whl (97 kB)
18:01:50.542	Collecting Jinja2>=2.10.1
18:01:50.547	  Downloading Jinja2-3.0.3-py3-none-any.whl (133 kB)
18:01:50.593	Collecting pyyaml-env-tag>=0.1
18:01:50.601	  Downloading pyyaml_env_tag-0.1-py3-none-any.whl (3.9 kB)
18:01:50.652	Collecting packaging>=20.5
18:01:50.657	  Downloading packaging-21.3-py3-none-any.whl (40 kB)
18:01:50.693	Collecting mergedeep>=1.3.4
18:01:50.698	  Downloading mergedeep-1.3.4-py3-none-any.whl (6.4 kB)
18:01:50.790	Collecting watchdog>=2.0
18:01:50.796	  Downloading watchdog-2.1.6-py3-none-manylinux2014_x86_64.whl (76 kB)
18:01:50.852	Collecting Markdown>=3.2.1
18:01:50.858	  Downloading Markdown-3.3.6-py3-none-any.whl (97 kB)
18:01:50.902	Collecting ghp-import>=1.0
18:01:50.908	  Downloading ghp_import-2.0.2-py3-none-any.whl (11 kB)
18:01:51.004	Collecting importlib-metadata>=3.10
18:01:51.016	  Downloading importlib_metadata-4.8.2-py3-none-any.whl (17 kB)
18:01:51.144	Collecting PyYAML>=3.10
18:01:51.151	  Downloading PyYAML-6.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (596 kB)
18:01:51.207	Collecting htmlmin>=0.1.4
18:01:51.212	  Downloading htmlmin-0.1.12.tar.gz (19 kB)
18:01:51.572	Collecting jsmin>=3.0.0
18:01:51.578	  Downloading jsmin-3.0.0.tar.gz (11 kB)
18:01:51.900	Collecting csscompressor>=0.9.5
18:01:51.907	  Downloading csscompressor-0.9.5.tar.gz (237 kB)
18:01:52.328	Collecting MarkupSafe>=2.0
18:01:52.333	  Downloading MarkupSafe-2.0.1-cp37-cp37m-manylinux2010_x86_64.whl (31 kB)
18:01:52.431	Collecting pyparsing!=3.0.5,>=2.0.2
18:01:52.436	  Downloading pyparsing-3.0.6-py3-none-any.whl (97 kB)
18:01:52.483	Collecting python-dateutil>=2.8.1
18:01:52.488	  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
18:01:52.553	Collecting zipp>=0.5
18:01:52.558	  Downloading zipp-3.6.0-py3-none-any.whl (5.3 kB)
18:01:52.603	Collecting typing-extensions>=3.6.4; python_version < "3.8"
18:01:52.624	  Downloading typing_extensions-4.0.0-py3-none-any.whl (22 kB)
18:01:52.666	Collecting six>=1.5
18:01:52.670	  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
18:01:52.680	Building wheels for collected packages: mkdocs-minify-plugin, htmlmin, jsmin, csscompressor
18:01:52.681	  Building wheel for mkdocs-minify-plugin (setup.py): started
18:01:53.042	  Building wheel for mkdocs-minify-plugin (setup.py): finished with status 'done'
18:01:53.043	  Created wheel for mkdocs-minify-plugin: filename=mkdocs_minify_plugin-0.5.0-py3-none-any.whl size=3300 sha256=ef0cc963579e6c05b41207b2f3f458f1c8f62eb25df09763ef945a1797ed06aa
18:01:53.043	  Stored in directory: /opt/buildhome/.cache/pip/wheels/90/37/fb/19754f0be67837344aca9096b4b3c2bc9fe462bbad480c8bc4
18:01:53.045	  Building wheel for htmlmin (setup.py): started
18:01:53.397	  Building wheel for htmlmin (setup.py): finished with status 'done'
18:01:53.398	  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27084 sha256=7220cda9e27b0644d6d1dead34b2b3456ce15cc5d31dfc6b32fd44675fc2babd
18:01:53.398	  Stored in directory: /opt/buildhome/.cache/pip/wheels/70/e1/52/5b14d250ba868768823940c3229e9950d201a26d0bd3ee8655
18:01:53.401	  Building wheel for jsmin (setup.py): started
18:01:53.757	  Building wheel for jsmin (setup.py): finished with status 'done'
18:01:53.758	  Created wheel for jsmin: filename=jsmin-3.0.0-py3-none-any.whl size=13875 sha256=edfcb5538646c32d6f61aa4dc947765d24cec1798e940bd47b36984fd7833311
18:01:53.758	  Stored in directory: /opt/buildhome/.cache/pip/wheels/aa/57/73/60e594ac2b8609a7fc2b1592d16b02d88fef3781392e13f5e6
18:01:53.760	  Building wheel for csscompressor (setup.py): started
18:01:54.129	  Building wheel for csscompressor (setup.py): finished with status 'done'
18:01:54.130	  Created wheel for csscompressor: filename=csscompressor-0.9.5-py3-none-any.whl size=240337 sha256=ffd85f7327d5989505be4b3d38a05fb559e2c3a22719ac66243c72048af421c8
18:01:54.131	  Stored in directory: /opt/buildhome/.cache/pip/wheels/4d/71/0b/a541c02576f1ce5efaa72addf79fe3f5e8f93fb9d64d73c9bf
18:01:54.132	Successfully built mkdocs-minify-plugin htmlmin jsmin csscompressor
18:01:54.244	Installing collected packages: zipp, typing-extensions, importlib-metadata, click, MarkupSafe, Jinja2, PyYAML, pyyaml-env-tag, pyparsing, packaging, mergedeep, watchdog, Markdown, six, python-dateutil, ghp-import, mkdocs, mkdocs-bootswatch, htmlmin, jsmin, csscompressor, mkdocs-minify-plugin
18:01:55.448	Successfully installed Jinja2-3.0.3 Markdown-3.3.6 MarkupSafe-2.0.1 PyYAML-6.0 click-8.0.3 csscompressor-0.9.5 ghp-import-2.0.2 htmlmin-0.1.12 importlib-metadata-4.8.2 jsmin-3.0.0 mergedeep-1.3.4 mkdocs-1.2.3 mkdocs-bootswatch-1.1 mkdocs-minify-plugin-0.5.0 packaging-21.3 pyparsing-3.0.6 python-dateutil-2.8.2 pyyaml-env-tag-0.1 six-1.16.0 typing-extensions-4.0.0 watchdog-2.1.6 zipp-3.6.0
18:01:55.577	WARNING: You are using pip version 20.2b1; however, version 21.3.1 is available.
18:01:55.577	You should consider upgrading via the '/opt/buildhome/python3.7/bin/python3.7 -m pip install --upgrade pip' command.
18:01:55.656	Pip dependencies installed
18:01:55.689	5.2 is already installed.
18:01:55.696	Using Swift version 5.2
18:01:55.696	Installing Hugo 0.54.0
18:01:56.238	Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
18:01:56.240	Started restoring cached go cache
18:01:56.243	Finished restoring cached go cache
18:01:56.270	go version go1.14.4 linux/amd64
18:01:56.277	go version go1.14.4 linux/amd64
18:01:56.278	Installing missing commands
18:01:56.278	Verify run directory
18:01:56.278	Executing user command: mkdocs build
18:01:56.546	INFO     -  Cleaning site directory
18:01:56.546	INFO     -  Building documentation to directory: /opt/buildhome/repo/site
18:01:56.554	Traceback (most recent call last):
18:01:56.554	  File "/opt/buildhome/python3.7/bin/mkdocs", line 8, in <module>
18:01:56.554	    sys.exit(cli())
18:01:56.554	  File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
18:01:56.554	    return self.main(*args, **kwargs)
18:01:56.554	  File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 1053, in main
18:01:56.554	    rv = self.invoke(ctx)
18:01:56.554	  File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
18:01:56.554	    return _process_result(sub_ctx.command.invoke(sub_ctx))
18:01:56.555	  File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
18:01:56.555	    return ctx.invoke(self.callback, **ctx.params)
18:01:56.555	  File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 754, in invoke
18:01:56.556	    return __callback(*args, **kwargs)
18:01:56.556	  File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/__main__.py", line 187, in build_command
18:01:56.556	    build.build(config.load_config(**kwargs), dirty=not clean)
18:01:56.556	  File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/commands/build.py", line 284, in build
18:01:56.556	    nav = get_navigation(files, config)
18:01:56.556	  File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/structure/nav.py", line 101, in get_navigation
18:01:56.556	    items = _data_to_navigation(nav_config, files, config)
18:01:56.556	  File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/structure/nav.py", line 160, in _data_to_navigation
18:01:56.556	    for item in data
18:01:56.556	  File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/structure/nav.py", line 160, in <listcomp>
18:01:56.556	    for item in data
18:01:56.556	  File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/structure/nav.py", line 153, in _data_to_navigation
18:01:56.556	    for key, value in data.items()
18:01:56.556	  File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/structure/nav.py", line 153, in <listcomp>
18:01:56.556	    for key, value in data.items()
18:01:56.556	  File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/structure/nav.py", line 163, in _data_to_navigation
18:01:56.556	    file = files.get_file_from_path(path)
18:01:56.557	  File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/structure/files.py", line 32, in get_file_from_path
18:01:56.557	    return self.src_paths.get(os.path.normpath(path))
18:01:56.557	  File "/opt/buildhome/python3.7/lib/python3.7/posixpath.py", line 340, in normpath
18:01:56.557	    path = os.fspath(path)
18:01:56.557	TypeError: expected str, bytes or os.PathLike object, not NoneType
18:01:56.582	Failed: build command exited with code: 1
`
Sorry to disturb you

**Comment by fu-sen** [comment]
You received this error after you edited `mkdocs.yml`.
https://github.com/soilland/Meal-Wiki/commit/0a91712074847bb5c44b827fe6b2f1a0f50fc5a7

It has a problem with the description of `nav`. I will quote the docs.
https://www.mkdocs.org/user-guide/configuration/#nav

This is clearly your mistake. It's not a problem with this project. Close this issues.

**Comment by soilland** [comment]
> You received this error after you edited `mkdocs.yml`. [soilland/Meal-Wiki@0a91712](https://github.com/soilland/Meal-Wiki/commit/0a91712074847bb5c44b827fe6b2f1a0f50fc5a7)
> 
> It has a problem with the description of `nav`. I will quote the docs. https://www.mkdocs.org/user-guide/configuration/#nav
> 
> This is clearly your mistake. It's not a problem with this project. Close this issues.

okay thank you🤦🏻I will fuck myself soon
